### ISSUE TITLE
Doesn't display for private repos

### ISSUE THREAD

**Issue by leotm** [softvar/github-plus#6]
Nice little extension!
But unfortunately it doesn't seem to work for private repos.
Would be great if all the deets would be visible to the owner.
Have the feeling Github OAuth would be required in the ext - but well worth it!

**Comment by softvar** [comment]
It does work for me. Can you try again?
Will be rolling out OAuth feature soon. you can try this -https://github.com/softvar/github-plus#github-api-rate-limiting for Rate Limiting workaround

**Comment by leotm** [comment]
Turns out this Chrome Ext was causing the download icon not to show 90% of the time:
https://github.com/harshjv/github-repo-size
Great stuff, would be good to be able to run both or even better add ^^ as a new feature.

**Comment by softvar** [comment]
@leotm Hope you're able to see the download icon now.
Will surely add a new feature -  to show repo size.

Closing this and opening a new one for the new feature request.

**Comment by softvar** [comment]
Hey @leotm ,

I was debugging the issue and found that for it to work for private repos, one has to use Github Access Token.
Follow the guide to use your Github Access Token for authenticated requests and even enjoy lot more requests per minute - https://github.com/softvar/github-plus#github-api-rate-limiting

**Comment by softvar** [comment]
Hey @leotm,
Now the extension show repo size too and the calls being made are now optimized.

Install the latest v0.1.5 -> https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd

**Comment by leotm** [comment]
Hey @softvar ,
Had to wait/refresh a few times, but can confirm now showing for private repos.
Great work!
