### ISSUE TITLE
Simpler Way To Add The GitHub Token

### ISSUE THREAD

**Issue by sprankhub** [softvar/github-plus#7]
Thanks for the great extension!

It would be cool if the GitHub token could be added in an options panel of the extension and not via the developer tools :-)

**Comment by softvar** [comment]
This is done in version 0.1.4. Please update the extension https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd.

Read the docs here https://github.com/softvar/github-plus#github-api-rate-limiting

Enjoy! 😄

**Comment by sprankhub** [comment]
Wow, that was fast. Cool, thanks! It would be even better if you checked the token from local storage and added it automatically after the update ;-)

**Comment by softvar** [comment]
Yea, that makes sense. But localStorage is still a fallback, so the old users who did store the key manually in localStorage will not get affected, their options page Token would appear empty. Will do that soon.
