### ISSUE TITLE
Icons and repo size rendering inconsistency

### ISSUE THREAD

**Issue by leotm** [softvar/github-plus#9]
Just took a short screen recording here:
[leotm-github-plus.zip](https://github.com/softvar/github-plus/files/434985/leotm-github-plus.zip)
Any ideas?
Cheers.

**Comment by softvar** [comment]
Hey @leotm 
Thanks for noticing and reporting the bug.

It has been fixed in v0.1.6, plz update the extension https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd

Closing this issue.

Cheers!
